import type { Metadata } from "next";
import { chineseFont } from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="zh"
      translate="no"
    >
      <body className={chineseFont.className}>{children}</body>
    </html>
  );
}
